# Generated by Django 4.2.6 on 2023-10-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_profile_profile_picture_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_picture.jpg', upload_to='profile_pictures'),
        ),
    ]
